parameters:
    kuborgh_queue.model.class: Kuborgh\Bundle\QueueBundle\Model\QueueModel
    kuborgh_queue.database.class: Kuborgh\Bundle\QueueBundle\Database\QueueDatabase

services:
    kuborgh_queue.model:
        class: %kuborgh_queue.model.class%
        calls:
            - [ setDoctrineRegistry, [@doctrine]]
            - [ setConcurrency, [%kuborgh_queue.concurrency%]]
            - [ setConsolePath, [%kuborgh_queue.console_path%]]
            - [ setLogger, [@logger]]
        tags:
            - { name: monolog.logger, channel: queue }

    kuborgh_queue.database:
        class: %kuborgh_queue.database.class%
        calls:
            - [ setParameter, ['database_host','%kuborgh_queue.database.host%']]
            - [ setParameter, ['database_name','%kuborgh_queue.database.name%']]
            - [ setParameter, ['database_user','%kuborgh_queue.database.user%']]
            - [ setParameter, ['database_password','%kuborgh_queue.database.password%']]
